// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnkmzjjbyivksowmhhnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJua216ampieWl2a3Nvd21oaG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDkyNDMsImV4cCI6MjA3Mjg4NTI0M30.2LFMyN6dp462f6_ajF2g0MLL6UMZMAncpoxowVNGP8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});